//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignService.Smev.XmlSigners.SignedXmlExt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NamespaceUri {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamespaceUri() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignService.Smev.XmlSigners.SignedXmlExt.NamespaceUri", typeof(NamespaceUri).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd.
        /// </summary>
        internal static string OasisWSSecuritySecext {
            get {
                return ResourceManager.GetString("OasisWSSecuritySecext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd.
        /// </summary>
        internal static string OasisWSSecurityUtility {
            get {
                return ResourceManager.GetString("OasisWSSecurityUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1.
        /// </summary>
        internal static string Smev3Types {
            get {
                return ResourceManager.GetString("Smev3Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1.
        /// </summary>
        internal static string Smev3TypesBasic {
            get {
                return ResourceManager.GetString("Smev3TypesBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://smev.gosuslugi.ru/rev111111.
        /// </summary>
        internal static string SmevMR244 {
            get {
                return ResourceManager.GetString("SmevMR244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://smev.gosuslugi.ru/rev120315.
        /// </summary>
        internal static string SmevMR255 {
            get {
                return ResourceManager.GetString("SmevMR255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1.
        /// </summary>
        internal static string SmevMR300 {
            get {
                return ResourceManager.GetString("SmevMR300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.xmlsoap.org/soap/envelope/.
        /// </summary>
        internal static string WSSoap11 {
            get {
                return ResourceManager.GetString("WSSoap11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2000/09/xmldsig#.
        /// </summary>
        internal static string WSXmlDSig {
            get {
                return ResourceManager.GetString("WSXmlDSig", resourceCulture);
            }
        }
    }
}
