namespace SignService.Smev.Services
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     Этот код создан программой.
	//     Исполняемая версия:4.0.30319.34209
	//
	//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
	//     повторной генерации кода.
	// </auto-generated>
	//------------------------------------------------------------------------------



	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "Void", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.SmevFault))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.AttachmentSizeLimitExceeded))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.QuoteLimitExceeded))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.SignatureVerificationFault))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.DestinationOverflow))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.BusinessDataTypeIsNotSupported))]
	public partial class Void : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "SmevFault", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.AttachmentSizeLimitExceeded))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.QuoteLimitExceeded))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.SignatureVerificationFault))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.DestinationOverflow))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SignService.Smev.Services.BusinessDataTypeIsNotSupported))]
	public partial class SmevFault : SignService.Smev.Services.Void
	{

		private string CodeField;

		private string DescriptionField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Code
		{
			get
			{
				return this.CodeField;
			}
			set
			{
				this.CodeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Description
		{
			get
			{
				return this.DescriptionField;
			}
			set
			{
				this.DescriptionField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "AttachmentSizeLimitExceeded", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
	public partial class AttachmentSizeLimitExceeded : SignService.Smev.Services.SmevFault
	{

		private long PermittedTotalAttachmentSizeField;

		private long RealTotalAttachmentSizeField;

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public long PermittedTotalAttachmentSize
		{
			get
			{
				return this.PermittedTotalAttachmentSizeField;
			}
			set
			{
				this.PermittedTotalAttachmentSizeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public long RealTotalAttachmentSize
		{
			get
			{
				return this.RealTotalAttachmentSizeField;
			}
			set
			{
				this.RealTotalAttachmentSizeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "QuoteLimitExceeded", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
	public partial class QuoteLimitExceeded : SignService.Smev.Services.SmevFault
	{

		private long RemainedTotalQuoteSizeField;

		private long RealTotalAttachmentSizeField;

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public long RemainedTotalQuoteSize
		{
			get
			{
				return this.RemainedTotalQuoteSizeField;
			}
			set
			{
				this.RemainedTotalQuoteSizeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
		public long RealTotalAttachmentSize
		{
			get
			{
				return this.RealTotalAttachmentSizeField;
			}
			set
			{
				this.RealTotalAttachmentSizeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "SignatureVerificationFault", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
	public partial class SignatureVerificationFault : SignService.Smev.Services.SmevFault
	{

		private SignService.Smev.Services.SignatureVerificationFault.SignatureVerificationFaultType SignatureVerificationFaultMemberField;

		[System.Runtime.Serialization.DataMemberAttribute(Name = "SignatureVerificationFault", IsRequired = true)]
		public SignService.Smev.Services.SignatureVerificationFault.SignatureVerificationFaultType SignatureVerificationFaultMember
		{
			get
			{
				return this.SignatureVerificationFaultMemberField;
			}
			set
			{
				this.SignatureVerificationFaultMemberField = value;
			}
		}

		[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
		[System.Runtime.Serialization.DataContractAttribute(Name = "SignatureVerificationFault.SignatureVerificationFaultType", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		public enum SignatureVerificationFaultType : int
		{

			[System.Runtime.Serialization.EnumMemberAttribute()]
			PoorSOAPEnvelopeFormat = 0,

			[System.Runtime.Serialization.EnumMemberAttribute()]
			NoSignatureFound = 1,

			[System.Runtime.Serialization.EnumMemberAttribute()]
			IncorrectSignatureTarget = 2,

			[System.Runtime.Serialization.EnumMemberAttribute()]
			SignatureIsInvalid = 3,

			[System.Runtime.Serialization.EnumMemberAttribute()]
			CertificateIsNotFound = 4,

			[System.Runtime.Serialization.EnumMemberAttribute()]
			CertificateIsExpired = 5,
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DestinationOverflow", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
	public partial class DestinationOverflow : SignService.Smev.Services.SmevFault
	{

		private string MessageBrokerAddressField;

		private string DestinationNameField;

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
		public string MessageBrokerAddress
		{
			get
			{
				return this.MessageBrokerAddressField;
			}
			set
			{
				this.MessageBrokerAddressField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 1)]
		public string DestinationName
		{
			get
			{
				return this.DestinationNameField;
			}
			set
			{
				this.DestinationNameField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "BusinessDataTypeIsNotSupported", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
	public partial class BusinessDataTypeIsNotSupported : SignService.Smev.Services.SmevFault
	{

		private string RootElementLocalNameField;

		private string RootElementNamespaceURIField;

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
		public string RootElementLocalName
		{
			get
			{
				return this.RootElementLocalNameField;
			}
			set
			{
				this.RootElementLocalNameField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
		public string RootElementNamespaceURI
		{
			get
			{
				return this.RootElementNamespaceURIField;
			}
			set
			{
				this.RootElementNamespaceURIField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
	[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
	public partial class InvalidContent : object, System.Xml.Serialization.IXmlSerializable
	{

		private System.Xml.XmlNode[] nodesField;

		private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("InvalidContent", "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1");

		public System.Xml.XmlNode[] Nodes
		{
			get
			{
				return this.nodesField;
			}
			set
			{
				this.nodesField = value;
			}
		}

		public void ReadXml(System.Xml.XmlReader reader)
		{
			this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
		}

		public void WriteXml(System.Xml.XmlWriter writer)
		{
			System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
		}

		public System.Xml.Schema.XmlSchema GetSchema()
		{
			return null;
		}

		public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
		{
			System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
			return typeName;
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	//[System.ServiceModel.ServiceContractAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1", ConfigurationName = "SignService.Smev.Services.SMEVMessageExchangePortType")]
	public interface SMEVMessageExchangePortType
	{

		//[System.ServiceModel.OperationContractAttribute(Action = "urn:SendRequest", ReplyAction = "*")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.BusinessDataTypeIsNotSupported), Action = "urn:SendRequest", Name = "BusinessDataTypeIsNotSupported", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.SmevFault), Action = "urn:SendRequest", Name = "TransactionCodeInvalid", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.SignatureVerificationFault), Action = "urn:SendRequest", Name = "SignatureVerificationFault", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.InvalidContent), Action = "urn:SendRequest", Name = "InvalidContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendRequest", Name = "AttachmentContentMiscoordination", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.AttachmentSizeLimitExceeded), Action = "urn:SendRequest", Name = "AttachmentSizeLimitExceeded", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.QuoteLimitExceeded), Action = "urn:SendRequest", Name = "QuoteLimitExceeded", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendRequest", Name = "AccessDenied", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendRequest", Name = "SenderIsNotRegistered", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendRequest", Name = "RecipientIsNotFound", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.DestinationOverflow), Action = "urn:SendRequest", Name = "DestinationOverflow", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendRequest", Name = "SMEVFailure", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendRequest", Name = "MessageIsAlreadySent", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendRequest", Name = "InvalidMessageIdFormat", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendRequest", Name = "StaleMessageId", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendRequest", Name = "EndOfLifeReached", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.XmlSerializerFormatAttribute()]
		SignService.Smev.Services.SendRequestResponse SendRequest(SignService.Smev.Services.SendRequestRequest request);

		// CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
		//[System.ServiceModel.OperationContractAttribute(Action = "urn:SendRequest", ReplyAction = "*")]
		System.Threading.Tasks.Task<SignService.Smev.Services.SendRequestResponse> SendRequestAsync(SignService.Smev.Services.SendRequestRequest request);

		//[System.ServiceModel.OperationContractAttribute(Action = "urn:SendResponse", ReplyAction = "*")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.BusinessDataTypeIsNotSupported), Action = "urn:SendResponse", Name = "BusinessDataTypeIsNotSupported", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.SignatureVerificationFault), Action = "urn:SendResponse", Name = "SignatureVerificationFault", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendResponse", Name = "SMEVFailure", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.InvalidContent), Action = "urn:SendResponse", Name = "InvalidContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendResponse", Name = "AttachmentContentMiscoordination", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.AttachmentSizeLimitExceeded), Action = "urn:SendResponse", Name = "AttachmentSizeLimitExceeded", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.QuoteLimitExceeded), Action = "urn:SendResponse", Name = "QuoteLimitExceeded", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendResponse", Name = "IncorrectResponseContentType", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendResponse", Name = "SenderIsNotRegistered", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendResponse", Name = "RecipientIsNotFound", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.DestinationOverflow), Action = "urn:SendResponse", Name = "DestinationOverflow", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendResponse", Name = "MessageIsAlreadySent", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendResponse", Name = "InvalidMessageIdFormat", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:SendResponse", Name = "StaleMessageId", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.XmlSerializerFormatAttribute()]
		SignService.Smev.Services.SendResponseResponse SendResponse(SignService.Smev.Services.SendResponseRequest request);

		// CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
		//[System.ServiceModel.OperationContractAttribute(Action = "urn:SendResponse", ReplyAction = "*")]
		System.Threading.Tasks.Task<SignService.Smev.Services.SendResponseResponse> SendResponseAsync(SignService.Smev.Services.SendResponseRequest request);

		// CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1) сообщения GetStatusRequest не соответствует значению по умолчанию (urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1).
		//[System.ServiceModel.OperationContractAttribute(Action = "urn:GetStatus", ReplyAction = "*")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.InvalidContent), Action = "urn:GetStatus", Name = "InvalidContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.SignatureVerificationFault), Action = "urn:GetStatus", Name = "SignatureVerificationFault", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetStatus", Name = "SenderIsNotRegistered", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetStatus", Name = "UnknownMessageType", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetStatus", Name = "SMEVFailure", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.XmlSerializerFormatAttribute()]
		SignService.Smev.Services.GetStatusResponse GetStatus(SignService.Smev.Services.GetStatusRequest request);

		//[System.ServiceModel.OperationContractAttribute(Action = "urn:GetStatus", ReplyAction = "*")]
		System.Threading.Tasks.Task<SignService.Smev.Services.GetStatusResponse> GetStatusAsync(SignService.Smev.Services.GetStatusRequest request);

		// CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1) сообщения GetRequestRequest не соответствует значению по умолчанию (urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1).
		//[System.ServiceModel.OperationContractAttribute(Action = "urn:GetRequest", ReplyAction = "*")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.InvalidContent), Action = "urn:GetRequest", Name = "InvalidContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.SignatureVerificationFault), Action = "urn:GetRequest", Name = "SignatureVerificationFault", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetRequest", Name = "SenderIsNotRegistered", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetRequest", Name = "UnknownMessageType", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetRequest", Name = "SMEVFailure", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.XmlSerializerFormatAttribute()]
		SignService.Smev.Services.GetRequestResponse GetRequest(SignService.Smev.Services.GetRequestRequest request);

		//[System.ServiceModel.OperationContractAttribute(Action = "urn:GetRequest", ReplyAction = "*")]
		System.Threading.Tasks.Task<SignService.Smev.Services.GetRequestResponse> GetRequestAsync(SignService.Smev.Services.GetRequestRequest request);

		// CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1) сообщения GetResponseRequest не соответствует значению по умолчанию (urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1).
		//[System.ServiceModel.OperationContractAttribute(Action = "urn:GetResponse", ReplyAction = "*")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.InvalidContent), Action = "urn:GetResponse", Name = "InvalidContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.SignatureVerificationFault), Action = "urn:GetResponse", Name = "SignatureVerificationFault", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetResponse", Name = "SenderIsNotRegistered", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetResponse", Name = "UnknownMessageType", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetResponse", Name = "SMEVFailure", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.XmlSerializerFormatAttribute()]
		SignService.Smev.Services.GetResponseResponse GetResponse(SignService.Smev.Services.GetResponseRequest request);

		//[System.ServiceModel.OperationContractAttribute(Action = "urn:GetResponse", ReplyAction = "*")]
		System.Threading.Tasks.Task<SignService.Smev.Services.GetResponseResponse> GetResponseAsync(SignService.Smev.Services.GetResponseRequest request);

		// CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1) сообщения AckRequest не соответствует значению по умолчанию (urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1).
		//[System.ServiceModel.OperationContractAttribute(Action = "urn:Ack", ReplyAction = "*")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.InvalidContent), Action = "urn:Ack", Name = "InvalidContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.SignatureVerificationFault), Action = "urn:Ack", Name = "SignatureVerificationFault", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:Ack", Name = "SenderIsNotRegistered", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:Ack", Name = "SMEVFailure", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:Ack", Name = "TargetMessageIsNotFound", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.XmlSerializerFormatAttribute()]
		SignService.Smev.Services.AckResponse Ack(SignService.Smev.Services.AckRequest request);

		//[System.ServiceModel.OperationContractAttribute(Action = "urn:Ack", ReplyAction = "*")]
		System.Threading.Tasks.Task<SignService.Smev.Services.AckResponse> AckAsync(SignService.Smev.Services.AckRequest request);

		// CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1) сообщения GetIncomingQueueStatisticsRequest не соответствует значению по умолчанию (urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1).
		//[System.ServiceModel.OperationContractAttribute(Action = "urn:GetIncomingQueueStatistics", ReplyAction = "*")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.InvalidContent), Action = "urn:GetIncomingQueueStatistics", Name = "InvalidContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.SignatureVerificationFault), Action = "urn:GetIncomingQueueStatistics", Name = "SignatureVerificationFault", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetIncomingQueueStatistics", Name = "SenderIsNotRegistered", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.FaultContractAttribute(typeof(SignService.Smev.Services.Void), Action = "urn:GetIncomingQueueStatistics", Name = "SMEVFailure", Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")]
		//[System.ServiceModel.XmlSerializerFormatAttribute()]
		SignService.Smev.Services.GetIncomingQueueStatisticsResponse GetIncomingQueueStatistics(SignService.Smev.Services.GetIncomingQueueStatisticsRequest request);

		//[System.ServiceModel.OperationContractAttribute(Action = "urn:GetIncomingQueueStatistics", ReplyAction = "*")]
		System.Threading.Tasks.Task<SignService.Smev.Services.GetIncomingQueueStatisticsResponse> GetIncomingQueueStatisticsAsync(SignService.Smev.Services.GetIncomingQueueStatisticsRequest request);
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class SenderProvidedRequestData
	{

		private string messageIDField;

		private string referenceMessageIDField;

		private string transactionCodeField;

		private string nodeIDField;

		private System.DateTime eOLField;

		private bool eOLFieldSpecified;

		private System.Xml.XmlElement messagePrimaryContentField;

		private System.Xml.XmlElement personalSignatureField;

		private AttachmentHeaderList attachmentHeaderListField;

		private RefAttachmentHeaderList refAttachmentHeaderListField;

		private SenderProvidedRequestDataBusinessProcessMetadata businessProcessMetadataField;

		private Void testMessageField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string MessageID
		{
			get
			{
				return this.messageIDField;
			}
			set
			{
				this.messageIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string ReferenceMessageID
		{
			get
			{
				return this.referenceMessageIDField;
			}
			set
			{
				this.referenceMessageIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string TransactionCode
		{
			get
			{
				return this.transactionCodeField;
			}
			set
			{
				this.transactionCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string NodeID
		{
			get
			{
				return this.nodeIDField;
			}
			set
			{
				this.nodeIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public System.DateTime EOL
		{
			get
			{
				return this.eOLField;
			}
			set
			{
				this.eOLField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool EOLSpecified
		{
			get
			{
				return this.eOLFieldSpecified;
			}
			set
			{
				this.eOLFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 5)]
		public System.Xml.XmlElement MessagePrimaryContent
		{
			get
			{
				return this.messagePrimaryContentField;
			}
			set
			{
				this.messagePrimaryContentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public System.Xml.XmlElement PersonalSignature
		{
			get
			{
				return this.personalSignatureField;
			}
			set
			{
				this.personalSignatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 7)]
		public AttachmentHeaderList AttachmentHeaderList
		{
			get
			{
				return this.attachmentHeaderListField;
			}
			set
			{
				this.attachmentHeaderListField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 8)]
		public RefAttachmentHeaderList RefAttachmentHeaderList
		{
			get
			{
				return this.refAttachmentHeaderListField;
			}
			set
			{
				this.refAttachmentHeaderListField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 9)]
		public SenderProvidedRequestDataBusinessProcessMetadata BusinessProcessMetadata
		{
			get
			{
				return this.businessProcessMetadataField;
			}
			set
			{
				this.businessProcessMetadataField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 10)]
		public Void TestMessage
		{
			get
			{
				return this.testMessageField;
			}
			set
			{
				this.testMessageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class AttachmentHeaderList
	{

		private AttachmentHeaderType[] attachmentHeaderField;

		private string tmpField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("AttachmentHeader", Order = 0)]
		public AttachmentHeaderType[] AttachmentHeader
		{
			get
			{
				return this.attachmentHeaderField;
			}
			set
			{
				this.attachmentHeaderField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string tmp
		{
			get
			{
				return this.tmpField;
			}
			set
			{
				this.tmpField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class AttachmentHeaderType
	{

		private string contentIdField;

		private string mimeTypeField;

		private byte[] signaturePKCS7Field;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string contentId
		{
			get
			{
				return this.contentIdField;
			}
			set
			{
				this.contentIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string MimeType
		{
			get
			{
				return this.mimeTypeField;
			}
			set
			{
				this.mimeTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 2)]
		public byte[] SignaturePKCS7
		{
			get
			{
				return this.signaturePKCS7Field;
			}
			set
			{
				this.signaturePKCS7Field = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class FSAuthInfo
	{

		private string uuidField;

		private string userNameField;

		private string passwordField;

		private string fileNameField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string uuid
		{
			get
			{
				return this.uuidField;
			}
			set
			{
				this.uuidField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string UserName
		{
			get
			{
				return this.userNameField;
			}
			set
			{
				this.userNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Password
		{
			get
			{
				return this.passwordField;
			}
			set
			{
				this.passwordField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string FileName
		{
			get
			{
				return this.fileNameField;
			}
			set
			{
				this.fileNameField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class AttachmentContentType
	{

		private string idField;

		private byte[] contentField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "ID", Order = 0)]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 1)]
		public byte[] Content
		{
			get
			{
				return this.contentField;
			}
			set
			{
				this.contentField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class RefAttachmentHeaderType
	{

		private string uuidField;

		private string hashField;

		private string mimeTypeField;

		private byte[] signaturePKCS7Field;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string uuid
		{
			get
			{
				return this.uuidField;
			}
			set
			{
				this.uuidField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Hash
		{
			get
			{
				return this.hashField;
			}
			set
			{
				this.hashField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string MimeType
		{
			get
			{
				return this.mimeTypeField;
			}
			set
			{
				this.mimeTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 3)]
		public byte[] SignaturePKCS7
		{
			get
			{
				return this.signaturePKCS7Field;
			}
			set
			{
				this.signaturePKCS7Field = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class RefAttachmentHeaderList
	{

		private RefAttachmentHeaderType[] refAttachmentHeaderField;

		private string tmpField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("RefAttachmentHeader", Order = 0)]
		public RefAttachmentHeaderType[] RefAttachmentHeader
		{
			get
			{
				return this.refAttachmentHeaderField;
			}
			set
			{
				this.refAttachmentHeaderField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string tmp
		{
			get
			{
				return this.tmpField;
			}
			set
			{
				this.tmpField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class SenderProvidedRequestDataBusinessProcessMetadata
	{

		private System.Xml.XmlElement[] anyField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
		public System.Xml.XmlElement[] Any
		{
			get
			{
				return this.anyField;
			}
			set
			{
				this.anyField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class AttachmentContentList
	{

		private AttachmentContentType[] attachmentContentField;

		private string tmpField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("AttachmentContent", Order = 0)]
		public AttachmentContentType[] AttachmentContent
		{
			get
			{
				return this.attachmentContentField;
			}
			set
			{
				this.attachmentContentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string tmp
		{
			get
			{
				return this.tmpField;
			}
			set
			{
				this.tmpField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class MessageMetadata
	{

		private string messageIdField;

		private MessageTypeType messageTypeField;

		private MessageMetadataSender senderField;

		private System.DateTime sendingTimestampField;

		private string messageBrokerField;

		private string destinationNameField;

		private MessageMetadataRecipient recipientField;

		private MessageMetadataSupplementaryData supplementaryDataField;

		private System.DateTime deliveryTimestampField;

		private bool deliveryTimestampFieldSpecified;

		private InteractionStatusType statusField;

		private bool statusFieldSpecified;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string MessageId
		{
			get
			{
				return this.messageIdField;
			}
			set
			{
				this.messageIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public MessageTypeType MessageType
		{
			get
			{
				return this.messageTypeField;
			}
			set
			{
				this.messageTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public MessageMetadataSender Sender
		{
			get
			{
				return this.senderField;
			}
			set
			{
				this.senderField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public System.DateTime SendingTimestamp
		{
			get
			{
				return this.sendingTimestampField;
			}
			set
			{
				this.sendingTimestampField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string MessageBroker
		{
			get
			{
				return this.messageBrokerField;
			}
			set
			{
				this.messageBrokerField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string DestinationName
		{
			get
			{
				return this.destinationNameField;
			}
			set
			{
				this.destinationNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public MessageMetadataRecipient Recipient
		{
			get
			{
				return this.recipientField;
			}
			set
			{
				this.recipientField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public MessageMetadataSupplementaryData SupplementaryData
		{
			get
			{
				return this.supplementaryDataField;
			}
			set
			{
				this.supplementaryDataField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 8)]
		public System.DateTime DeliveryTimestamp
		{
			get
			{
				return this.deliveryTimestampField;
			}
			set
			{
				this.deliveryTimestampField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool DeliveryTimestampSpecified
		{
			get
			{
				return this.deliveryTimestampFieldSpecified;
			}
			set
			{
				this.deliveryTimestampFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 9)]
		public InteractionStatusType Status
		{
			get
			{
				return this.statusField;
			}
			set
			{
				this.statusField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool StatusSpecified
		{
			get
			{
				return this.statusFieldSpecified;
			}
			set
			{
				this.statusFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public enum MessageTypeType
	{

		/// <remarks/>
		REQUEST,

		/// <remarks/>
		BROADCAST,

		/// <remarks/>
		RESPONSE,

		/// <remarks/>
		CANCEL,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class MessageMetadataSender
	{

		private string mnemonicField;

		private string humanReadableNameField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string Mnemonic
		{
			get
			{
				return this.mnemonicField;
			}
			set
			{
				this.mnemonicField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string HumanReadableName
		{
			get
			{
				return this.humanReadableNameField;
			}
			set
			{
				this.humanReadableNameField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class MessageMetadataRecipient
	{

		private string mnemonicField;

		private string humanReadableNameField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string Mnemonic
		{
			get
			{
				return this.mnemonicField;
			}
			set
			{
				this.mnemonicField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string HumanReadableName
		{
			get
			{
				return this.humanReadableNameField;
			}
			set
			{
				this.humanReadableNameField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class MessageMetadataSupplementaryData
	{

		private string detectedContentTypeNameField;

		private InteractionTypeType interactionTypeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string DetectedContentTypeName
		{
			get
			{
				return this.detectedContentTypeNameField;
			}
			set
			{
				this.detectedContentTypeNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public InteractionTypeType InteractionType
		{
			get
			{
				return this.interactionTypeField;
			}
			set
			{
				this.interactionTypeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public enum InteractionTypeType
	{

		/// <remarks/>
		PGU2OIV,

		/// <remarks/>
		OIV2OIV,

		/// <remarks/>
		OIV2sameOIV,

		/// <remarks/>
		Charger2PaymentGate,

		/// <remarks/>
		PaymentGate2Treasury,

		/// <remarks/>
		OIV2Treasury,

		/// <remarks/>
		other,

		/// <remarks/>
		NotDetected,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public enum InteractionStatusType
	{

		/// <remarks/>
		doesNotExist,

		/// <remarks/>
		requestIsQueued,

		/// <remarks/>
		requestIsAcceptedBySmev,

		/// <remarks/>
		requestIsRejectedBySmev,

		/// <remarks/>
		underProcessing,

		/// <remarks/>
		responseIsAcceptedBySmev,

		/// <remarks/>
		cancelled,

		/// <remarks/>
		responseIsDelivered,
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	//[System.ServiceModel.MessageContractAttribute(WrapperName = "SendRequestRequest", WrapperNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", IsWrapped = true)]
	public partial class SendRequestRequest
	{

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 0)]
		public SignService.Smev.Services.SenderProvidedRequestData SenderProvidedRequestData;

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 1)]
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
		public SignService.Smev.Services.AttachmentContentList AttachmentContentList;

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 2)]
		public System.Xml.XmlElement CallerInformationSystemSignature;

		public SendRequestRequest()
		{
		}

		public SendRequestRequest(SignService.Smev.Services.SenderProvidedRequestData SenderProvidedRequestData, SignService.Smev.Services.AttachmentContentList AttachmentContentList, System.Xml.XmlElement CallerInformationSystemSignature)
		{
			this.SenderProvidedRequestData = SenderProvidedRequestData;
			this.AttachmentContentList = AttachmentContentList;
			this.CallerInformationSystemSignature = CallerInformationSystemSignature;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	//[System.ServiceModel.MessageContractAttribute(WrapperName = "SendRequestResponse", WrapperNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", IsWrapped = true)]
	public partial class SendRequestResponse
	{

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 0)]
		public SignService.Smev.Services.MessageMetadata MessageMetadata;

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 1)]
		public System.Xml.XmlElement SMEVSignature;

		public SendRequestResponse()
		{
		}

		public SendRequestResponse(SignService.Smev.Services.MessageMetadata MessageMetadata, System.Xml.XmlElement SMEVSignature)
		{
			this.MessageMetadata = MessageMetadata;
			this.SMEVSignature = SMEVSignature;
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class SenderProvidedResponseData
	{

		private string messageIDField;

		private string toField;

		private object[] itemsField;

		private ItemsChoiceType[] itemsElementNameField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string MessageID
		{
			get
			{
				return this.messageIDField;
			}
			set
			{
				this.messageIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string To
		{
			get
			{
				return this.toField;
			}
			set
			{
				this.toField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("AsyncProcessingStatus", typeof(AsyncProcessingStatus), Order = 2)]
		[System.Xml.Serialization.XmlElementAttribute("PersonalSignature", typeof(System.Xml.XmlElement), Order = 2)]
		[System.Xml.Serialization.XmlElementAttribute("RequestRejected", typeof(SenderProvidedResponseDataRequestRejected), Order = 2)]
		[System.Xml.Serialization.XmlElementAttribute("RequestStatus", typeof(SenderProvidedResponseDataRequestStatus), Order = 2)]
		[System.Xml.Serialization.XmlElementAttribute("AttachmentHeaderList", typeof(AttachmentHeaderList), Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 2)]
		[System.Xml.Serialization.XmlElementAttribute("MessagePrimaryContent", typeof(System.Xml.XmlElement), Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 2)]
		[System.Xml.Serialization.XmlElementAttribute("RefAttachmentHeaderList", typeof(RefAttachmentHeaderList), Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 2)]
		[System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
		public object[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 3)]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public ItemsChoiceType[] ItemsElementName
		{
			get
			{
				return this.itemsElementNameField;
			}
			set
			{
				this.itemsElementNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class AsyncProcessingStatus
	{

		private string originalMessageIdField;

		private InteractionStatusType statusCategoryField;

		private string statusDetailsField;

		private SmevFault smevFaultField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string OriginalMessageId
		{
			get
			{
				return this.originalMessageIdField;
			}
			set
			{
				this.originalMessageIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public InteractionStatusType StatusCategory
		{
			get
			{
				return this.statusCategoryField;
			}
			set
			{
				this.statusCategoryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string StatusDetails
		{
			get
			{
				return this.statusDetailsField;
			}
			set
			{
				this.statusDetailsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public SmevFault SmevFault
		{
			get
			{
				return this.smevFaultField;
			}
			set
			{
				this.smevFaultField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class SenderProvidedResponseDataRequestRejected
	{

		private RejectCode rejectionReasonCodeField;

		private string rejectionReasonDescriptionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public RejectCode RejectionReasonCode
		{
			get
			{
				return this.rejectionReasonCodeField;
			}
			set
			{
				this.rejectionReasonCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string RejectionReasonDescription
		{
			get
			{
				return this.rejectionReasonDescriptionField;
			}
			set
			{
				this.rejectionReasonDescriptionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public enum RejectCode
	{

		/// <remarks/>
		ACCESS_DENIED,

		/// <remarks/>
		NO_DATA,

		/// <remarks/>
		UNKNOWN_REQUEST_DESCRIPTION,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class SenderProvidedResponseDataRequestStatus
	{

		private int statusCodeField;

		private SenderProvidedResponseDataRequestStatusStatusParameter[] statusParameterField;

		private string statusDescriptionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public int StatusCode
		{
			get
			{
				return this.statusCodeField;
			}
			set
			{
				this.statusCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("StatusParameter", Order = 1)]
		public SenderProvidedResponseDataRequestStatusStatusParameter[] StatusParameter
		{
			get
			{
				return this.statusParameterField;
			}
			set
			{
				this.statusParameterField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string StatusDescription
		{
			get
			{
				return this.statusDescriptionField;
			}
			set
			{
				this.statusDescriptionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class SenderProvidedResponseDataRequestStatusStatusParameter
	{

		private string keyField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string Key
		{
			get
			{
				return this.keyField;
			}
			set
			{
				this.keyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", IncludeInSchema = false)]
	public enum ItemsChoiceType
	{

		/// <remarks/>
		AsyncProcessingStatus,

		/// <remarks/>
		PersonalSignature,

		/// <remarks/>
		RequestRejected,

		/// <remarks/>
		RequestStatus,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1:Attachmen" +
			"tHeaderList")]
		AttachmentHeaderList,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1:MessagePr" +
			"imaryContent")]
		MessagePrimaryContent,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1:RefAttach" +
			"mentHeaderList")]
		RefAttachmentHeaderList,
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	//[System.ServiceModel.MessageContractAttribute(WrapperName = "SendResponseRequest", WrapperNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", IsWrapped = true)]
	public partial class SendResponseRequest
	{

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 0)]
		public SignService.Smev.Services.SenderProvidedResponseData SenderProvidedResponseData;

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 1)]
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
		public SignService.Smev.Services.AttachmentContentList AttachmentContentList;

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 2)]
		public System.Xml.XmlElement CallerInformationSystemSignature;

		public SendResponseRequest()
		{
		}

		public SendResponseRequest(SignService.Smev.Services.SenderProvidedResponseData SenderProvidedResponseData, SignService.Smev.Services.AttachmentContentList AttachmentContentList, System.Xml.XmlElement CallerInformationSystemSignature)
		{
			this.SenderProvidedResponseData = SenderProvidedResponseData;
			this.AttachmentContentList = AttachmentContentList;
			this.CallerInformationSystemSignature = CallerInformationSystemSignature;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	//[System.ServiceModel.MessageContractAttribute(WrapperName = "SendResponseResponse", WrapperNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", IsWrapped = true)]
	public partial class SendResponseResponse
	{

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 0)]
		public SignService.Smev.Services.MessageMetadata MessageMetadata;

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 1)]
		public System.Xml.XmlElement SMEVSignature;

		public SendResponseResponse()
		{
		}

		public SendResponseResponse(SignService.Smev.Services.MessageMetadata MessageMetadata, System.Xml.XmlElement SMEVSignature)
		{
			this.MessageMetadata = MessageMetadata;
			this.SMEVSignature = SMEVSignature;
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class Timestamp
	{

		private string idField;

		private System.DateTime valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public System.DateTime Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class SmevAsyncProcessingMessage
	{

		private AsyncProcessingStatusData itemField;

		private System.Xml.XmlElement sMEVSignatureField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("AsyncProcessingStatusData", Order = 0)]
		public AsyncProcessingStatusData Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public System.Xml.XmlElement SMEVSignature
		{
			get
			{
				return this.sMEVSignatureField;
			}
			set
			{
				this.sMEVSignatureField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class AsyncProcessingStatusData
	{

		private AsyncProcessingStatus asyncProcessingStatusField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AsyncProcessingStatus AsyncProcessingStatus
		{
			get
			{
				return this.asyncProcessingStatusField;
			}
			set
			{
				this.asyncProcessingStatusField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	//[System.ServiceModel.MessageContractAttribute(WrapperName = "GetStatusRequest", WrapperNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", IsWrapped = true)]
	public partial class GetStatusRequest
	{

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
		public SignService.Smev.Services.Timestamp Timestamp;

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 1)]
		public System.Xml.XmlElement CallerInformationSystemSignature;

		public GetStatusRequest()
		{
		}

		public GetStatusRequest(SignService.Smev.Services.Timestamp Timestamp, System.Xml.XmlElement CallerInformationSystemSignature)
		{
			this.Timestamp = Timestamp;
			this.CallerInformationSystemSignature = CallerInformationSystemSignature;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	//[System.ServiceModel.MessageContractAttribute(WrapperName = "GetStatusResponse", WrapperNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", IsWrapped = true)]
	public partial class GetStatusResponse
	{

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 0)]
		public SignService.Smev.Services.SmevAsyncProcessingMessage SmevAsyncProcessingMessage;

		public GetStatusResponse()
		{
		}

		public GetStatusResponse(SignService.Smev.Services.SmevAsyncProcessingMessage SmevAsyncProcessingMessage)
		{
			this.SmevAsyncProcessingMessage = SmevAsyncProcessingMessage;
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class MessageTypeSelector
	{

		private string namespaceURIField;

		private string rootElementLocalNameField;

		private System.DateTime timestampField;

		private string nodeIDField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 0)]
		public string NamespaceURI
		{
			get
			{
				return this.namespaceURIField;
			}
			set
			{
				this.namespaceURIField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "NCName", Order = 1)]
		public string RootElementLocalName
		{
			get
			{
				return this.rootElementLocalNameField;
			}
			set
			{
				this.rootElementLocalNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public System.DateTime Timestamp
		{
			get
			{
				return this.timestampField;
			}
			set
			{
				this.timestampField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string NodeID
		{
			get
			{
				return this.nodeIDField;
			}
			set
			{
				this.nodeIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class GetRequestResponseRequestMessage
	{

		private object[] itemsField;

		private System.Xml.XmlElement sMEVSignatureField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Cancel", typeof(Cancel), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("Request", typeof(Request), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("AttachmentContentList", typeof(AttachmentContentList), Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 0)]
		public object[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public System.Xml.XmlElement SMEVSignature
		{
			get
			{
				return this.sMEVSignatureField;
			}
			set
			{
				this.sMEVSignatureField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class Cancel
	{

		private MessageReference messageReferenceField;

		private string messageIDField;

		private MessageMetadata messageMetadataField;

		private System.Xml.XmlElement senderInformationSystemSignatureField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 0)]
		public MessageReference MessageReference
		{
			get
			{
				return this.messageReferenceField;
			}
			set
			{
				this.messageReferenceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string MessageID
		{
			get
			{
				return this.messageIDField;
			}
			set
			{
				this.messageIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public MessageMetadata MessageMetadata
		{
			get
			{
				return this.messageMetadataField;
			}
			set
			{
				this.messageMetadataField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public System.Xml.XmlElement SenderInformationSystemSignature
		{
			get
			{
				return this.senderInformationSystemSignatureField;
			}
			set
			{
				this.senderInformationSystemSignatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class MessageReference
	{

		private string idField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class Request
	{

		private SenderProvidedRequestData senderProvidedRequestDataField;

		private MessageMetadata messageMetadataField;

		private FSAttachmentsList fSAttachmentsListField;

		private string replyToField;

		private System.Xml.XmlElement senderInformationSystemSignatureField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public SenderProvidedRequestData SenderProvidedRequestData
		{
			get
			{
				return this.senderProvidedRequestDataField;
			}
			set
			{
				this.senderProvidedRequestDataField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public MessageMetadata MessageMetadata
		{
			get
			{
				return this.messageMetadataField;
			}
			set
			{
				this.messageMetadataField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 2)]
		public FSAttachmentsList FSAttachmentsList
		{
			get
			{
				return this.fSAttachmentsListField;
			}
			set
			{
				this.fSAttachmentsListField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string ReplyTo
		{
			get
			{
				return this.replyToField;
			}
			set
			{
				this.replyToField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public System.Xml.XmlElement SenderInformationSystemSignature
		{
			get
			{
				return this.senderInformationSystemSignatureField;
			}
			set
			{
				this.senderInformationSystemSignatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class FSAttachmentsList
	{

		private FSAuthInfo[] fSAttachmentField;

		private string tmpField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("FSAttachment", Order = 0)]
		public FSAuthInfo[] FSAttachment
		{
			get
			{
				return this.fSAttachmentField;
			}
			set
			{
				this.fSAttachmentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string tmp
		{
			get
			{
				return this.tmpField;
			}
			set
			{
				this.tmpField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	//[System.ServiceModel.MessageContractAttribute(WrapperName = "GetRequestRequest", WrapperNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", IsWrapped = true)]
	public partial class GetRequestRequest
	{

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
		public SignService.Smev.Services.MessageTypeSelector MessageTypeSelector;

		//[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", Order = 1)]
		public System.Xml.XmlElement CallerInformationSystemSignature;

		public GetRequestRequest()
		{
		}

		public GetRequestRequest(SignService.Smev.Services.MessageTypeSelector MessageTypeSelector, System.Xml.XmlElement CallerInformationSystemSignature)
		{
			this.MessageTypeSelector = MessageTypeSelector;
			this.CallerInformationSystemSignature = CallerInformationSystemSignature;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	//[System.ServiceModel.MessageContractAttribute(WrapperName = "GetRequestResponse", WrapperNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1", IsWrapped = true)]
	public partial class GetRequestResponse
	{
		public SignService.Smev.Services.GetRequestResponseRequestMessage RequestMessage;

		public GetRequestResponse()
		{
		}

		public GetRequestResponse(SignService.Smev.Services.GetRequestResponseRequestMessage RequestMessage)
		{
			this.RequestMessage = RequestMessage;
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class GetResponseResponseResponseMessage
	{

		private Response responseField;

		private AttachmentContentList attachmentContentListField;

		private System.Xml.XmlElement sMEVSignatureField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Response Response
		{
			get
			{
				return this.responseField;
			}
			set
			{
				this.responseField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 1)]
		public AttachmentContentList AttachmentContentList
		{
			get
			{
				return this.attachmentContentListField;
			}
			set
			{
				this.attachmentContentListField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public System.Xml.XmlElement SMEVSignature
		{
			get
			{
				return this.sMEVSignatureField;
			}
			set
			{
				this.sMEVSignatureField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class Response
	{

		private string originalMessageIdField;

		private string originalTransactionCodeField;

		private string referenceMessageIDField;

		private SenderProvidedResponseData senderProvidedResponseDataField;

		private MessageMetadata messageMetadataField;

		private FSAttachmentsList fSAttachmentsListField;

		private System.Xml.XmlElement senderInformationSystemSignatureField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string OriginalMessageId
		{
			get
			{
				return this.originalMessageIdField;
			}
			set
			{
				this.originalMessageIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string OriginalTransactionCode
		{
			get
			{
				return this.originalTransactionCodeField;
			}
			set
			{
				this.originalTransactionCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string ReferenceMessageID
		{
			get
			{
				return this.referenceMessageIDField;
			}
			set
			{
				this.referenceMessageIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public SenderProvidedResponseData SenderProvidedResponseData
		{
			get
			{
				return this.senderProvidedResponseDataField;
			}
			set
			{
				this.senderProvidedResponseDataField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public MessageMetadata MessageMetadata
		{
			get
			{
				return this.messageMetadataField;
			}
			set
			{
				this.messageMetadataField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1", Order = 5)]
		public FSAttachmentsList FSAttachmentsList
		{
			get
			{
				return this.fSAttachmentsListField;
			}
			set
			{
				this.fSAttachmentsListField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public System.Xml.XmlElement SenderInformationSystemSignature
		{
			get
			{
				return this.senderInformationSystemSignatureField;
			}
			set
			{
				this.senderInformationSystemSignatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public partial class GetResponseRequest
	{
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
		public SignService.Smev.Services.MessageTypeSelector MessageTypeSelector;

		public System.Xml.XmlElement CallerInformationSystemSignature;

		public GetResponseRequest()
		{
		}

		public GetResponseRequest(SignService.Smev.Services.MessageTypeSelector MessageTypeSelector, System.Xml.XmlElement CallerInformationSystemSignature)
		{
			this.MessageTypeSelector = MessageTypeSelector;
			this.CallerInformationSystemSignature = CallerInformationSystemSignature;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public partial class GetResponseResponse
	{
		[System.Xml.Serialization.XmlElementAttribute("ResponseMessage")]
		public SignService.Smev.Services.GetResponseResponseResponseMessage Item;

		public GetResponseResponse()
		{
		}

		public GetResponseResponse(SignService.Smev.Services.GetResponseResponseResponseMessage Item)
		{
			this.Item = Item;
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
	public partial class AckTargetMessage
	{

		private string idField;

		private bool acceptedField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool accepted
		{
			get
			{
				return this.acceptedField;
			}
			set
			{
				this.acceptedField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public partial class AckRequest
	{
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
		public SignService.Smev.Services.AckTargetMessage AckTargetMessage;

		public System.Xml.XmlElement CallerInformationSystemSignature;

		public AckRequest()
		{
		}

		public AckRequest(SignService.Smev.Services.AckTargetMessage AckTargetMessage, System.Xml.XmlElement CallerInformationSystemSignature)
		{
			this.AckTargetMessage = AckTargetMessage;
			this.CallerInformationSystemSignature = CallerInformationSystemSignature;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public partial class AckResponse
	{

		public AckResponse()
		{
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1")]
	public partial class GetIncomingQueueStatisticsResponseQueueStatistics
	{

		private string queueNameField;

		private long pendingMessageNumberField;

		private bool pendingMessageNumberFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string queueName
		{
			get
			{
				return this.queueNameField;
			}
			set
			{
				this.queueNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public long pendingMessageNumber
		{
			get
			{
				return this.pendingMessageNumberField;
			}
			set
			{
				this.pendingMessageNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool pendingMessageNumberSpecified
		{
			get
			{
				return this.pendingMessageNumberFieldSpecified;
			}
			set
			{
				this.pendingMessageNumberFieldSpecified = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public partial class GetIncomingQueueStatisticsRequest
	{
		public string NodeID;

		[System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1")]
		public SignService.Smev.Services.Timestamp Timestamp;

		public System.Xml.XmlElement CallerInformationSystemSignature;

		public GetIncomingQueueStatisticsRequest()
		{
		}

		public GetIncomingQueueStatisticsRequest(string NodeID, SignService.Smev.Services.Timestamp Timestamp, System.Xml.XmlElement CallerInformationSystemSignature)
		{
			this.NodeID = NodeID;
			this.Timestamp = Timestamp;
			this.CallerInformationSystemSignature = CallerInformationSystemSignature;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public partial class GetIncomingQueueStatisticsResponse
	{
		[System.Xml.Serialization.XmlElementAttribute("QueueStatistics")]
		public SignService.Smev.Services.GetIncomingQueueStatisticsResponseQueueStatistics[] QueueStatistics;

		public GetIncomingQueueStatisticsResponse()
		{
		}

		public GetIncomingQueueStatisticsResponse(SignService.Smev.Services.GetIncomingQueueStatisticsResponseQueueStatistics[] QueueStatistics)
		{
			this.QueueStatistics = QueueStatistics;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public partial class SMEVMessageExchangePortTypeClient
	{
		public System.Threading.Tasks.Task<SignService.Smev.Services.GetIncomingQueueStatisticsResponse> GetIncomingQueueStatisticsAsync(string NodeID, SignService.Smev.Services.Timestamp Timestamp, System.Xml.XmlElement CallerInformationSystemSignature)
		{
			SignService.Smev.Services.GetIncomingQueueStatisticsRequest inValue = new SignService.Smev.Services.GetIncomingQueueStatisticsRequest();
			inValue.NodeID = NodeID;
			inValue.Timestamp = Timestamp;
			inValue.CallerInformationSystemSignature = CallerInformationSystemSignature;
			return ((SignService.Smev.Services.SMEVMessageExchangePortType)(this)).GetIncomingQueueStatisticsAsync(inValue);
		}
	}
}
